### ISSUE TITLE
New home for helm-secrets 

### ISSUE THREAD

**Issue by 5nafu** [hiberbee/github-action-helm#9]
zendesk deprecated the helm-secrets plugin and gave maintenance to Jan-Otto Kröpke:

```
Deprecation Info
  Please note, this project is no longer being maintained.
  Link to active helm-secret plugin could be found in helm documentation: https://helm.sh/docs/community/related/#helm-plugins
Installed plugin: secrets
```
Pleae update the source in https://github.com/hiberbee/github-action-helm/blob/f3a6cf3c1e0f6624ecd8da6799ee1b00074b4b60/src/index.js#L5036 to https://github.com/jkroepke/helm-secrets

**Comment by vladyslavvolkov** [comment]
Thanks, @5nafu, 
Sorry for long response, I've updated action to [1.3.0](https://github.com/hiberbee/github-action-helm/releases/tag/1.3.0), included latest helm/helmfile and link you've mentioned. See latest workflow run, seems to be okay. Thanks!
